# -*- coding: utf-8 -*-
"""CampanhasMarketing-Grafos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12R8WoDvWHIETzMP2jmsF1F0YrISX2NkX

Fase 0 - Configuração e Importação
"""

!pip install networkx
!pip install pyvis

import matplotlib.pyplot as plt
import networkx as nx
from pyvis.network import Network
import pandas as pd